---
- name: Retrieve logs of Kubernetes deployment pods
  hosts: localhost
  gather_facts: no
  vars:
    namespace: default  # Change this to your desired namespace
    deployment_name: web  # Change this to your deployment name
    log_output_dir: ./k8s_logs  # Local directory to store logs

  tasks:
    - name: Ensure log output directory exists
      ansible.builtin.file:
        path: "{{ log_output_dir }}"
        state: directory
        mode: '0755'

    - name: Get pods for deployment
      ansible.builtin.command: >
        kubectl get pods -n {{ namespace }}
        -l app={{ deployment_name }}
        -o jsonpath='{.items[*].metadata.name}'
      register: pod_list_raw
      changed_when: false

    - name: Convert pod list string to list
      ansible.builtin.set_fact:
        pod_list: "{{ pod_list_raw.stdout.split() }}"

    - name: Get logs for each pod
      ansible.builtin.shell: >
        kubectl logs -n {{ namespace }} {{ item }} > {{ log_output_dir }}/{{ item }}.log
      loop: "{{ pod_list }}"
      changed_when: false
